"""init

Revision ID: 4853571a0c0c
Revises: 
Create Date: 2022-03-21 00:45:05.561575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4853571a0c0c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('price_in_rub', sa.String(length=50), nullable=True),
    sa.Column('price_in_eur', sa.String(length=50), nullable=True),
    sa.Column('price_note', sa.String(length=50), nullable=True),
    sa.Column('placement_date', sa.String(length=50), nullable=True),
    sa.Column('photo_url', sa.String(length=50), nullable=True),
    sa.Column('url_address', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_announcements_id'), 'announcements', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_announcements_id'), table_name='announcements')
    op.drop_table('announcements')
    # ### end Alembic commands ###
